# Generated by Django 4.0.4 on 2022-05-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('callsign', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('cleared', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=4)),
                ('eobt', models.TimeField()),
                ('tsat', models.TimeField()),
                ('destination', models.CharField(max_length=4)),
                ('ttot', models.TimeField()),
            ],
        ),
    ]
