# Generated by Django 4.0.4 on 2022-05-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotstreamer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
