# Generated by Django 4.0.4 on 2022-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotstreamer', '0003_slot_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=264)),
                ('room_id', models.CharField(max_length=264)),
            ],
        ),
    ]
