# Generated by Django 4.0.4 on 2022-06-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slotstreamer', '0004_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='session',
            name='room_id',
            field=models.CharField(max_length=264, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slotstreamer.session'),
        ),
    ]
