# Generated by Django 4.0.4 on 2022-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictoken',
            name='private_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publictoken',
            name='public_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
