# Generated by Django 4.0.4 on 2022-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_publictoken_private_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publictoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='publictoken',
            name='public_token',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
