# Generated by Django 4.0.4 on 2022-06-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slotstreamer', '0005_remove_session_session_id_alter_session_room_id_and_more'),
        ('authentication', '0005_alter_useradditionaldata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionaldata',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slotstreamer.session'),
        ),
    ]
